### ISSUE TITLE
Add ability to use settings.json from any place

### ISSUE THREAD

**Issue by sprilukin** [Jaspersoft/faf-tool#2]
It would be great to have ability to install faf-tool globally and then pass path to settings.json file 
for example:

$ npm install faf-tool -g
$ cd < project folder >
$ faf-tool setup -s < path-to-setttings >

**Comment by nesterone** [comment]
$ faf-tool setup
by default it would search in current dir ;-)

**Comment by sprilukin** [comment]
ok, in this case it become a nice-to-have feature )

**Comment by sprilukin** [comment]
I've made a pull request which resolve this issue
https://github.com/Jaspersoft/faf-tool/pull/5

**Comment by sprilukin** [comment]
Pull request changed: https://github.com/Jaspersoft/faf-tool/pull/6
and it's already merged, so issue could be closed after testing.
